name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 📝 Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "SERVICE_ID=${{ secrets.SERVICE_ID }}" >> .env
          echo "ACCOUNT_SID=${{ secrets.ACCOUNT_SID }}" >> .env
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env

      - name: 🚀 Start Server
        run: npm start
